server:
  port: 8989
app:
  name: Challenge Dimensa Contacts API
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
