server:
  port: ${API_PORT:8989}
app:
  name: Challenge Dimensa Contacts API
spring:
  datasource:
    url: ${JDBC_DATASOURCE_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
